/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final_grupo1;// Declaración del paquete del archivo

import Conexion.conexion;// Importar la clase 'conexion' desde el paquete 'Conexion'
import java.awt.Color;
import java.sql.Connection; // Importar la clase 'Connection' del paquete 'java.sql'
import java.sql.*;// Importar todas las clases del paquete 'java.sql'
import javax.swing.JOptionPane;// Importar la clase 'JOptionPane' del paquete 'javax.swing'
import java.util.logging.*;// Importar las clases relacionadas con el registro de eventos

public class INGRESAR extends javax.swing.JFrame {// Declaración de la clase INGRESAR que extiende de javax.swing.JFrame

    conexion con = new conexion(); // Crear una instancia de la clase 'conexion'
    Connection cn = con.conectar(); // Establecer una conexión utilizando el método 'conectar' de la instancia 'con'
    PreparedStatement ps;// Declarar una variable 'ps' para preparar una sentencia SQL
    ResultSet rs;   // Declarar una variable 'rs' para almacenar el resultado de una consulta  
    /**
     * Creates new form INGRESAR
     */
    public INGRESAR() {// Constructor de la clase
        initComponents();// Inicialización de los componentes de la interfaz gráfica
        setLocationRelativeTo(null);// Establece la ubicación de la ventana en el centro de la pantalla
        
    }
    private void LimpiarCajas(){
        tipo.setSelectedIndex(0);// Establecer el índice seleccionado en el elemento 0 del combo box 'tipo'
        txtcantidad.setText(null); // Limpiar el contenido del campo de texto 'txtcantidad'
        txtingreso.setText(null); // Limpiar el contenido del campo de texto 'txtingreso'
        txtvencimiento.setText(null);// Limpiar el contenido del campo de texto 'txtvencimiento'
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();
        txtcantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        txtvencimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRAR PRODUCTO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 320, 60));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo de Producto:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("REGISTRAR PRODUCTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        tipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar:", "Leche", "Queso", "Crema", "Mantequilla", "Yogurt" }));
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, -1));

        txtcantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        jPanel2.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 190, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Vencimiento:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de Ingreso:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        txtingreso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresoActionPerformed(evt);
            }
        });
        jPanel2.add(txtingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, -1));

        txtvencimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtvencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvencimientoActionPerformed(evt);
            }
        });
        jPanel2.add(txtvencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 190, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo de Producto:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtproducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductoActionPerformed(evt);
            }
        });
        txtproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtproductoKeyTyped(evt);
            }
        });
        jPanel2.add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 190, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-health-and-vitality-milk-dairy-products-poster-background-material-image_126084.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 590, 520));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipo de Producto:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();// Coloca la ventana actual en la parte posterior (oculta la ventana)
        setVisible(false);// Establece la visibilidad de la ventana actual como falsa (oculta la ventana)
        new MENU().toFront();// Crea una nueva instancia de la clase MENU y la coloca en el frente (hace visible la ventana MENU)
        new MENU().setState(java.awt.Frame.NORMAL);// Establece el estado de la ventana MENU como normal
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Guardar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped

    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingresoActionPerformed

    private void txtvencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvencimientoActionPerformed

    private void txtproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductoActionPerformed

    private void txtproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductoKeyTyped
        // TODO add your handling code here:
        //estas lineas de codigo sirven para poder hacer que el textfield de codigo de producto no se pueda ingresar nada ya que es auto incrementable
        txtproducto.setEditable(false);
        txtproducto.setEnabled(false);
        txtproducto.setFocusable(false);
    }//GEN-LAST:event_txtproductoKeyTyped
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INGRESAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new INGRESAR().setVisible(true);
        });
    }
public void Guardar(){
    
    try{
        // Preparar la sentencia SQL para insertar registros en la tabla 'lacteos'
        PreparedStatement pps= cn.prepareStatement("INSERT INTO lacteos(Tipo_Producto,Cantidad,Fecha_de_Ingreso,Fecha_de_Vencimiento) VALUES(?,?,?,?)");
         // Establecer los valores de los parámetros en la sentencia SQL
        pps.setString(1, (String) tipo.getSelectedItem());// Tipo de Producto
        pps.setString(2, txtcantidad.getText());// Cantidad
        pps.setString(3, txtingreso.getText());// Fecha de Ingreso
        pps.setString(4, txtvencimiento.getText()); // Fecha de Vencimiento
        pps.executeUpdate();// Ejecutar la sentencia SQL para insertar el registro en la tabla 'lacteos'
        JOptionPane.showMessageDialog(null, "Producto Registrado");// Mostrar un mensaje de éxito
        LimpiarCajas();// Llamar al método 'LimpiarCajas()' para limpiar los campos de texto
        }catch(SQLException ex) {
            Logger.getLogger(INGRESAR.class.getName()).log(Level.SEVERE, null, ex);// Registrar y mostrar el mensaje de error en el registro de eventos
        }}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtingreso;
    javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtvencimiento;
    // End of variables declaration//GEN-END:variables
}
